import { IControl } from "../../allinterface/settingsform/ISettingsLibForm";

export const formControls: IControl[] = [
    {
        "CanChange": 0,
        "IsRequired": 0,
        "GroupName": "APForm_DeviceByModelFilter",
        "GroupNameDesc": "",
        "SubGroupEntID": "F388AA00-AB4B-4773-8F0C-06F899C0D73A",
        "SubGroupName": "FormControl",
        "SubGroupNameDesc": "",
        "_AP": "Manufacturer",
        "PropertyLabel": "Manufacturer",
        "NameDesc": "Manufacturer",
        "DefaultAPValue": "",
        "Value": "",
        "ValueDesc": "",
        "SortOrder": 4,
        "MaxInstances": 0,
        "InputMask": "",
        "RegEx": "",
        "DisplayGroupControl": "",
        "DisplayControl": "ComboBoxControl",
        "ChangeEvent": "",
        "Secured": true,
        "IsNZ": true,
        "EntID": "8EF6B4FF-2D60-4744-88FB-618E89912415",
        "RecID": "9716F160-C506-48F5-BEFE-D0C4A852BEF4",
        "LastUpdated": "11/19/2024",
        "EntityName": "AP",
        "Name": "Manufacturer",
        "disabled": false,
        "MfgAcronym": "2BM",
        "type": "isManufacturer"
    },
    {
        "CanChange": 0,
        "IsRequired": 0,
        "GroupName": "APForm_DeviceByModelFilter",
        "GroupNameDesc": "",
        "SubGroupEntID": "F388AA00-AB4B-4773-8F0C-06F899C0D73A",
        "SubGroupName": "FormControl",
        "SubGroupNameDesc": "",
        "_AP": "Equipment Type",
        "PropertyLabel": "Equipment Type",
        "NameDesc": "Equipment Type",
        "DefaultAPValue": "",
        "Value": "",
        "ValueDesc": "",
        "SortOrder": 5,
        "MaxInstances": 0,
        "InputMask": "",
        "RegEx": "",
        "DisplayGroupControl": "",
        "DisplayControl": "ComboBoxControl",
        "ChangeEvent": "",
        "Secured": true,
        "IsNZ": true,
        "EntID": "4FF25E62-F330-4596-8B33-146A8E4CD7B8",
        "RecID": "9BC06A56-0051-4606-94BE-2FB5F489BC33",
        "LastUpdated": "11/19/2024",
        "EntityName": "AP",
        "Name": "Equipment Type",
        "disabled": false,
        "type": "isEquipmentTypes"
    },
    {
        "CanChange": 0,
        "IsRequired": 0,
        "GroupName": "APForm_DeviceByModelFilter",
        "GroupNameDesc": "",
        "SubGroupEntID": "F388AA00-AB4B-4773-8F0C-06F899C0D73A",
        "SubGroupName": "FormControl",
        "SubGroupNameDesc": "",
        "_AP": "Product Number",
        "PropertyLabel": "Product Number",
        "NameDesc": "Product Number",
        "DefaultAPValue": "",
        "Value": "",
        "ValueDesc": "",
        "SortOrder": 7,
        "MaxInstances": 0,
        "InputMask": "",
        "RegEx": "",
        "DisplayGroupControl": "",
        "DisplayControl": "ComboBoxControl",
        "ChangeEvent": "",
        "Secured": true,
        "IsNZ": true,
        "EntID": "F630D965-D832-4E06-9BA0-F886ECE46C89",
        "RecID": "9EC32129-5A6F-4071-8D5D-8F6A9F4A1461",
        "LastUpdated": "11/19/2024",
        "EntityName": "AP",
        "Name": "Product Number",
        "disabled": false,
        "type": "isProdNo"
    }
];
